#!/bin/bash

# Start mongodb
mongod &

# nvm install 
wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.10.0/install.sh | bash

#sudo chmod -R 777 /usr/sbin/
source ~/.nvm/nvm.sh;
nvm install 0.11.12;
nvm use 0.11.12;
#cd /home/freebrain/projects/btc-trader/agent;
cd /Users/ghouchex/traderbot/agent
npm start;
