#!/bin/bash
sudo curl https://raw.githubusercontent.com/creationix/nvm/v0.7.0/install.sh | sh;
sudo chmod -R 777 /usr/sbin/
source ~/.nvm/nvm.sh;
nvm install 0.11.12;
nvm use 0.11.12;
cd /home/freebrain/projects/btc-trader/agent;
npm start;
